version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: airport
      POSTGRES_TZ: Asia/Jerusalem
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432"
    networks:
      pg_network:  
        ipv4_address: 172.19.0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admind
    ports:
      - "8080:80"
    networks:
      pg_network:
        ipv4_address: 172.19.0.3

networks:
  pg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
