# Generated by Django 5.1.3 on 2025-02-18 17:17

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[(base.models.FlightStatus['ACTIVE'], 'active'), (base.models.FlightStatus['CANCELED'], 'canceled'), (base.models.FlightStatus['TOOKOFF'], 'tookoff'), (base.models.FlightStatus['LANDED'], 'landed')], default='active'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(base.models.FlightStatus['ACTIVE'], 'active'), (base.models.FlightStatus['CANCELED'], 'canceled'), (base.models.FlightStatus['TOOKOFF'], 'tookoff'), (base.models.FlightStatus['LANDED'], 'landed')], default='active'),
        ),
    ]
