# Generated by Django 5.1.3 on 2025-02-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_flight_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('tookoff', 'tookoff'), ('landed', 'landed')], default='active'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('tookoff', 'tookoff'), ('landed', 'landed')], default='active'),
        ),
    ]
