# Generated by Django 5.1.1 on 2024-11-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userrole_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportuser',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userrole'),
        ),
    ]
