# Generated by Django 5.0.7 on 2024-11-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_airportuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='base.country'),
        ),
    ]
