# Generated by Django 5.0.7 on 2024-11-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_airline_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
