# Generated by Django 5.1.3 on 2024-12-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_ticket'),
        ('base', '0026_auto_20241208_1434'),
    ]

    operations = [
    ]
