# Generated by Django 5.1.3 on 2025-02-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20241208_1220'),
        ('base', '0027_merge_0025_ticket_0026_auto_20241208_1434'),
    ]

    operations = [
    ]
