# Generated by Django 5.0.7 on 2024-11-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_airportuser_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='airport_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
