# Generated by Django 5.1.1 on 2024-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_airline_flight_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_card_no',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
