# Generated by Django 5.0.7 on 2024-11-17 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_user_id_customer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='User',
        ),
        migrations.AddField(
            model_name='admin',
            name='airport_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.airportuser'),
        ),
        migrations.AddField(
            model_name='airline',
            name='airport_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='base.airportuser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='airport_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='base.airportuser'),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='country_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='base.country'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='airportuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='base.flight'),
        ),
    ]
