# Generated by Django 5.0.7 on 2024-11-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_admin_user_id_remove_airline_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='airport_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.airportuser'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='airport_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='base.airportuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='airport_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='base.airportuser'),
        ),
    ]
