# Generated by Django 5.0.7 on 2024-11-21 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_airportuser_groups_airportuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='airport_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
