# Generated by Django 5.1.3 on 2024-12-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_flight_is_active'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION deactivate_expired_flights()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.departure_time <= CURRENT_TIMESTAMP THEN
                    NEW.is_active = FALSE;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS deactivate_expired_flights();"
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER check_flight_status
            BEFORE INSERT OR UPDATE ON base_flight
            FOR EACH ROW
            EXECUTE FUNCTION deactivate_expired_flights();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS check_flight_status ON base_flight;"
        ),
    ]
