# Generated by Django 5.1.3 on 2024-12-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20241208_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
