# Generated by Django 5.1.3 on 2024-12-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='base.customer')),
                ('flight_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='base.flight')),
            ],
        ),
    ]
